version: '3.5'

services:

  ## UFO GENERATOR API #########
  ufo-generator:
    container_name: ufo-generator
    hostname: ufo-generator
    build:
      context: ./ufo-generator
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_MQ_URL: "${AWS_MQ_URL}"
      AWS_MQ_USER: "${AWS_MQ_USER}"
      AWS_MQ_PWD: "${AWS_MQ_PWD}"
    ports:
      - "8080:8080"
    networks:
      - ufo_network
  ## UFO RADAR API #########
  ufo-radar:
    container_name: ufo-radar
    hostname: ufo-radar
    build:
      context: ./ufo-radar
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_MQ_URL: "${AWS_MQ_URL}"
      AWS_MQ_USER: "${AWS_MQ_USER}"
      AWS_MQ_PWD: "${AWS_MQ_PWD}"
    ports:
      - "8082:8082"
    networks:
      - ufo_network
  ## UFO SERVER SENT EVENT #########
  ufo-sse:
    container_name: ufo-sse
    hostname: ufo-sse
    build:
      context: ./ufo-sse
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_MQ_URL: "${AWS_MQ_URL}"
      AWS_MQ_USER: "${AWS_MQ_USER}"
      AWS_MQ_PWD: "${AWS_MQ_PWD}"
    ports:
      - "8081:8081"
    networks:
      - ufo_network
  ## UFO DETECTION SERVICE (INSTANCE 1)#########
  ufo-radar-detection_1:
    container_name: ufo-radar-detection_1
    hostname: ufo-radar-detection_1
    environment:
      AWS_MQ_URL: "${AWS_MQ_URL}"
      AWS_MQ_USER: "${AWS_MQ_USER}"
      AWS_MQ_PWD: "${AWS_MQ_PWD}"
    build:
      context: ./ufo-radar-detection
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - ufo_network
  ## UFO DETECTION SERVICE (INSTANCE 2)#########
  ufo-radar-detection_2:
    container_name: ufo-radar-detection_2
    hostname: ufo-radar-detection_2
    environment:
      AWS_MQ_URL: "${AWS_MQ_URL}"
      AWS_MQ_USER: "${AWS_MQ_USER}"
      AWS_MQ_PWD: "${AWS_MQ_PWD}"
    build:
      context: ./ufo-radar-detection
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - ufo_network
networks:
    ufo_network:
      external:
        name: ufo_network
