version: '3.5'

services:
  ## APACHE HTTPD #########
  httpd:
    container_name: httpd
    build:
      context: ./httpd
    ports:
      - "80:80"
    networks:
      - ufo_network

networks:
    ufo_network:
      external:
        name: ufo_network
