version: '3.5'

services:
  ## RABBITMQ BROKER #########
  rabbitmq_broker:
    container_name: rabbitmq_broker
    build:
      context: ./rabbitmq
    ports:
      - "4369:4369"
      - "25672:25672"
      - "15672:15672"
      - "5672:5672"
    networks:
      - ufo_network

networks:
    ufo_network:
      name: ufo_network
