version: '3.5'

services:
  ## RABBITMQ BROKER #########
  rabbitmq_broker:
    container_name: rabbitmq_broker
    build:
      context: ./rabbitmq
    ports:
      - "4369:4369"
      - "25672:25672"
      - "15672:15672"
      - "5672:5672"
    networks:
      - ufo_network
  ## APACHE HTTPD #########
  httpd:
    container_name: httpd
    build:
      context: ./httpd
    ports:
      - "80:80"
    networks:
      - ufo_network
  ## UFO GENERATOR API #########
  ufo-generator:
    container_name: ufo-generator
    hostname: ufo-generator
    build:
      context: ./ufo-generator
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
    networks:
      - ufo_network
  ## UFO RADAR API #########
  ufo-radar:
    container_name: ufo-radar
    hostname: ufo-radar
    build:
      context: ./ufo-radar
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8082:8082"
    networks:
      - ufo_network
  ## UFO SERVER SENT EVENT #########
  ufo-sse:
    container_name: ufo-sse
    hostname: ufo-sse
    build:
      context: ./ufo-sse
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8081:8081"
    networks:
      - ufo_network
  ## UFO DETECTION SERVICE (INSTANCE 1) #########
  ufo-radar-detection_1:
    container_name: ufo-radar-detection_1
    hostname: ufo-radar-detection_1
    build:
      context: ./ufo-radar-detection
      dockerfile: src/main/docker/Dockerfile.native
    networks:
      - ufo_network
  ## UFO DETECTION SERVICE (INSTANCE 2) #########
  ufo-radar-detection_2:
    container_name: ufo-radar-detection_2
    hostname: ufo-radar-detection_2
    build:
      context: ./ufo-radar-detection
      dockerfile: src/main/docker/Dockerfile.native
    networks:
      - ufo_network

networks:
    ufo_network:
      name: ufo_network