---
apiVersion: "v1"
kind: "List"
items:

###### UFO AMQP BROKER ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-broker"
    name: "ufo-broker"
  spec:
    ports:
      - name: "tcp"
        port: 4369
        targetPort: 4369
      - name: "cli"
        port: 25672
        targetPort: 25672
      - name: "amqps"
        port: 15672
        targetPort: 15672
      - name: "amqp"
        port: 5672
        targetPort: 5672
    selector:
      app: "ufo-broker"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-broker"
    name: "ufo-broker"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "ufo-broker"
    template:
      metadata:
        labels:
          app: "ufo-broker"
      spec:
        containers:
          - env:
              - name: "KUBERNETES_NAMESPACE"
                valueFrom:
                  fieldRef:
                    fieldPath: "metadata.namespace"
            image: "guillaumemtheodo/ufo-broker:1.0-SNAPSHOT"
            imagePullPolicy: "IfNotPresent"
            name: "ufo-broker"
            ports:
              - containerPort: 4369
                name: "tcp"
                protocol: "TCP"
              - containerPort: 25672
                name: "cli"
                protocol: "TCP"
              - containerPort: 15672
                name: "amqps"
                protocol: "TCP"
              - containerPort: 5672
                name: "amqp"
                protocol: "TCP"

###### UFO RADAR APPLICATION ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-radar"
    name: "ufo-radar"
  spec:
    ports:
    - name: "http"
      port: 8082
      targetPort: 8082
    selector:
      app: "ufo-radar"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-radar"
    name: "ufo-radar"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "ufo-radar"
    template:
      metadata:
        labels:
          app: "ufo-radar"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "guillaumemtheodo/ufo-radar:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "ufo-radar"
          ports:
            - containerPort: 8082
              name: "tcp"
              protocol: "TCP"

###### UFO RADAR DETECTION APPLICATION ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-radar-detection"
    name: "ufo-radar-detection"
  spec:
    ports:
    - name: "http"
      port: 8085
      targetPort: 8085
    selector:
      app: "ufo-radar-detection"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-radar-detection"
    name: "ufo-radar-detection"
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: "ufo-radar-detection"
    template:
      metadata:
        labels:
          app: "ufo-radar-detection"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "guillaumemtheodo/ufo-radar-detection:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "ufo-radar-detection"
          ports:
          - containerPort: 8085
            name: "http"
            protocol: "TCP"

###### UFO SSE APPLICATION ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-sse"
    name: "ufo-sse"
  spec:
    ports:
    - name: "http"
      port: 8081
      targetPort: 8081
    selector:
      app: "ufo-sse"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-sse"
    name: "ufo-sse"
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: "ufo-sse"
    template:
      metadata:
        labels:
          app: "ufo-sse"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "guillaumemtheodo/ufo-sse:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "ufo-sse"
          ports:
          - containerPort: 8081
            name: "http"
            protocol: "TCP"

###### UFO GENERATOR APPLICATION ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-generator"
    name: "ufo-generator"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "ufo-generator"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-generator"
    name: "ufo-generator"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "ufo-generator"
    template:
      metadata:
        labels:
          app: "ufo-generator"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "guillaumemtheodo/ufo-generator:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "ufo-generator"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"

###### UFO HTTPD APPLICATION ##########
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "ufo-httpd"
    name: "ufo-httpd"
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    selector:
      app: "ufo-httpd"
    type: "LoadBalancer"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "ufo-httpd"
    name: "ufo-httpd"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "ufo-httpd"
    template:
      metadata:
        labels:
          app: "ufo-httpd"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "guillaumemtheodo/ufo-httpd:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "ufo-httpd"
          ports:
          - containerPort: 80
            name: "http"
            protocol: "TCP"